Remove some raw SQL strings
pluginsGLPI/news pull request #116
Opened 2022-12-29 01:26 UTC by cconard96

2023-07-05 11:50 UTC, cedric-anne requested changes

2023-07-05 11:50 UTC, cedric-anne commented on inc/alert.class.php
> +                     "$ttable.items_id" => $_SESSION['glpiactiveprofile']['id'],
Condition on `all_items` is missing.
```suggestion
                     'OR' => [
                         "$ttable.items_id" => $_SESSION['glpiactiveprofile']['id'],
                         "$ttable.all_items" => 1,
                     ],
```

2023-07-05 11:50 UTC, cedric-anne commented on inc/alert.class.php
> +         'SELECT' => ["$table.*"],
There was a `DISTINCT` keyword in previous code.
```suggestion
         'SELECT' => ["$table.*"],
         'DISTINCT' => true,
```

2024-04-05 06:55 UTC, stonebuzz approved these changes

2024-04-05 07:12 UTC, trasher approved these changes

2024-04-05 07:26 UTC, stonebuzz requested changes

2024-04-05 07:51 UTC, stonebuzz approved these changes

2024-04-05 08:29 UTC, Rom1-B approved these changes

2024-04-08 06:40 UTC, cedric-anne commented on inc/alert.class.php
> +                        ["$table.date_start" => $today],
Il would probably be a little faster.
```suggestion
                        ["$table.date_start" => ['<=', $today]],
```

2024-04-08 06:40 UTC, cedric-anne commented on inc/alert.class.php
> +                        ["$table.date_end" => $today],
```suggestion
                        ["$table.date_end" => ['>=', $today]],
```

2024-04-08 06:40 UTC, cedric-anne commented on inc/alert.class.php
> +            $criteria['WHERE'][] = [$entity_sql];
No need to encapsulate it, it is already an array.
```suggestion
            $criteria['WHERE'][] = $entity_sql;
```

2024-04-08 06:40 UTC, cedric-anne commented on inc/alert.class.php
> +        }
All of these conditions are mandatory and can be placed at the `AND` root level.
```suggestion
        if (!empty($login_sql)) {
            $criteria['WHERE'][] = $login_sql;
        }
        if (!empty($show_central_sql)) {
            $criteria['WHERE'][] = $show_central_sql;
        }
        if (!empty($show_helpdesk_sql)) {
            $criteria['WHERE'][] = $show_helpdesk_sql;
        }
```

2024-04-08 06:40 UTC, cedric-anne commented on inc/alert.class.php
> +                [$login_show_hidden_sql],
No need to encapsulate it (see comment related to other conditions).
```suggestion
                $login_show_hidden_sql,
```

2024-04-08 07:02 UTC, stonebuzz commented
tested and approved

2024-04-08 07:18 UTC, cedric-anne approved these changes

2024-04-08 07:18 UTC, merged